os:
  edit: nvim

c:
  git: true
  dirs: build
  files: README.md main.c Makefile
c++:
  git: true
  dirs: build
  files: README.md main.cpp CMakeLists.txt
java:
  git: false
  dirs: out src
  files: README.md src/Main.java

